{"timestamp": "2025-01-16-22-10-08", "message": "Module error while formatting daily room measurements for 2025-01-16.: unexpected error while loading data\\logs\\temperature_and_humidity\\temperature_and_humidity.json.2025-01-16 to array of JSONs: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/data\\\\logs\\\\temperature_and_humidity\\\\temperature_and_humidity.json.2025-01-16' (FileNotFoundError).", "severity": 3, "origin": "data_formatter.py:58 --> project.py/load_ndjson_to_json_list:1395", "origin_timestamp": "2025-01-16-22-08-33", "registration_timestamp": "2025-01-16-22-08-33"}
{"timestamp": "2025-01-16-22-10-11", "message": "Module error while formatting daily room set temps for 2025-01-16.: unexpected error while loading data\\logs\\service_execution\\heating_control\\heating_control.json.2025-01-16 to array of JSONs: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/data\\\\logs\\\\service_execution\\\\heating_control\\\\heating_control.json.2025-01-16' (FileNotFoundError).", "severity": 3, "origin": "data_formatter.py:95 --> project.py/load_ndjson_to_json_list:1395", "origin_timestamp": "2025-01-16-22-08-33", "registration_timestamp": "2025-01-16-22-08-33"}
{"timestamp": "2025-01-16-22-10-12", "message": "Module error while formatting external temp for 2025-01-16.: unexpected error while loading data\\logs\\external_temp\\external_temp.json.2025-01-16 to array of JSONs: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/data\\\\logs\\\\external_temp\\\\external_temp.json.2025-01-16' (FileNotFoundError).", "severity": 3, "origin": "data_formatter.py:129 --> project.py/load_ndjson_to_json_list:1395", "origin_timestamp": "2025-01-16-22-08-33", "registration_timestamp": "2025-01-16-22-08-33"}
{"timestamp": "2025-01-16-22-10-15", "message": "Module error while formatting gas consumption for 2025-01-16.: unexpected error while loading data\\logs\\gas_consumption\\gas_relay_turns.json.2025-01-16 to array of JSONs: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/data\\\\logs\\\\gas_consumption\\\\gas_relay_turns.json.2025-01-16' (FileNotFoundError).", "severity": 3, "origin": "data_formatter.py:162 --> project.py/load_ndjson_to_json_list:1395", "origin_timestamp": "2025-01-16-22-08-33", "registration_timestamp": "2025-01-16-22-08-33"}
{"timestamp": "2025-01-16-22-10-16", "message": "Module error while formatting heating state for 2025-01-16.: unexpected error while loading data\\logs\\service_execution\\heating_control\\heating_control.json.2025-01-16 to array of JSONs: [Errno 2] No such file or directory: '/media/pi/program_stick/kazanfutes/data\\\\logs\\\\service_execution\\\\heating_control\\\\heating_control.json.2025-01-16' (FileNotFoundError).", "severity": 3, "origin": "data_formatter.py:210 --> project.py/load_ndjson_to_json_list:1395", "origin_timestamp": "2025-01-16-22-08-33", "registration_timestamp": "2025-01-16-22-08-33"}
