{"timestamp": "2025-02-15-06-30-07", "message": "Module error while trying to update local heating control config: failed to set up Google Sheets API: The read operation timed out (TimeoutError).", "severity": 2, "origin": "schedule_and_config_updater.py/update_local_heating_control_config:88 --> project.py/download_google_sheet_to_2D_array:1722", "origin_timestamp": "2025-02-15-06-25-53", "registration_timestamp": "2025-02-15-06-25-53"}
{"timestamp": "2025-02-15-23-30-06", "message": "Module error while trying to scrape and log external temperature: failed to interact with node 'system' via patch: HTTPSConnectionPool(host='kazanfutes-71b78-default-rtdb.europe-west1.firebasedatabase.app', port=443): Max retries exceeded with url: /system/state.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf5178870>: Failed to establish a new connection: [Errno 101] Network is unreachable')) (ConnectionError).", "severity": 2, "origin": "external_temp_scraper_and_logger.py:11 --> project.py/write:286 --> project.py/interact:266", "origin_timestamp": "2025-02-15-23-27-18", "registration_timestamp": "2025-02-15-23-27-18"}
