{"timestamp": "2025-02-02-03-35-05", "message": "Module error while trying to update local copy of weekly_cycle/2: failed to set up Google Sheets API: <HttpError 503 when requesting https://sheets.googleapis.com/v4/spreadsheets/1OmcLOB4OvFqmVw6Jq1lxu5fo7FchPBNMM6MFoNgM7r4?alt=json returned \"The service is currently unavailable.\". Details: \"The service is currently unavailable.\"> (HttpError).", "severity": 3, "origin": "schedule_and_config_updater.py/update_local_scheduling_files:173 --> project.py/download_google_sheet_to_2D_array:1617", "origin_timestamp": "2025-02-02-03-31-08", "registration_timestamp": "2025-02-02-03-31-08"}
{"timestamp": "2025-02-02-12-05-04", "message": "Module error while trying to sync data and config with repo: git command failed: Command '['git', 'add', '.']' returned non-zero exit status 128. (CalledProcessError).", "severity": 2, "origin": "data_and_config_uploader.py:9 --> project.py/sync_dir_with_repo:376", "origin_timestamp": "2025-02-02-12-00-12", "registration_timestamp": "2025-02-02-12-00-12"}
