{"timestamp": "2025-02-19-16-25-05", "message": "Module error while trying to initialize heating control: failed to interact with node 'system' via get: HTTPSConnectionPool(host='kazanfutes-71b78-default-rtdb.europe-west1.firebasedatabase.app', port=443): Max retries exceeded with url: /system/.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf54a1f30>: Failed to establish a new connection: [Errno 101] Network is unreachable')) (ConnectionError).", "severity": 3, "origin": "heating_control.py:15 --> project.py/__init__:246 --> project.py/read:272 --> project.py/interact:266", "origin_timestamp": "2025-02-19-16-23-51", "registration_timestamp": "2025-02-19-16-23-51"}
