{"timestamp": "2025-01-18-00-25-06", "message": "Module error while trying to update local heating control config: failed to download sheet '<googleapiclient.discovery.Resource object at 0xf48a3b70>' from spreadsheet 'Kaz\u00e1nf\u0171t\u00e9s heating control config': The read operation timed out (TimeoutError).", "severity": 2, "origin": "schedule_and_config_updater.py/update_local_heating_control_config:86 --> project.py/download_google_sheet_to_2D_array:1617", "origin_timestamp": "2025-01-18-00-21-05", "registration_timestamp": "2025-01-18-00-21-05"}
{"timestamp": "2025-01-18-20-15-06", "message": "Module error while trying to scrape and log external temperature: error during external temperature scraping: HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=47.4984&longitude=19.0405&current_weather=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf51e4ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) (ConnectionError).", "severity": 2, "origin": "external_temp_scraper_and_logger.py:9 --> project.py/scrape_external_temperature:621", "origin_timestamp": "2025-01-18-20-12-18", "registration_timestamp": "2025-01-18-20-12-18"}
