{"timestamp": "2025-01-19-00-05-04", "message": "Module error while trying to sync data and config with repo: git command failed: Command '['git', 'add', '.']' returned non-zero exit status 128. (CalledProcessError).", "severity": 2, "origin": "data_and_config_uploader.py:9 --> project.py/sync_dir_with_repo:374", "origin_timestamp": "2025-01-19-00-00-13", "registration_timestamp": "2025-01-19-00-00-13"}
{"timestamp": "2025-01-19-10-10-04", "message": "Module error while trying to initialize heating control: failed to interact with node 'system' via get: HTTPSConnectionPool(host='kazanfutes-71b78-default-rtdb.europe-west1.firebasedatabase.app', port=443): Max retries exceeded with url: /system/.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)'))) (SSLError).", "severity": 3, "origin": "heating_control.py:15 --> project.py/__init__:243 --> project.py/read:269 --> project.py/interact:263", "origin_timestamp": "2025-01-19-10-08-55", "registration_timestamp": "2025-01-19-10-08-55"}
