{"timestamp": "2024-10-15-00-00-03", "message": "Unexpected error while trying to update local heating control config: cannot access local variable 'spreadsheet_metadata' where it is not associated with a value.", "severity": 2, "origin": "schedule_and_ config_updater.py/update_local_heating_control_config:56 --> project.py/download_google_sheet_to_2D_array:1523", "origin_timestamp": "2024-10-14-21-45-35", "registration_timestamp": "2024-10-14-21-45-35"}
{"timestamp": "2024-10-15-00-00-03", "message": "Unexpected error while trying to update local copy of weekly_cycle/1: download_csv_to_2D_array() takes 1 positional argument but 2 were given.", "severity": 3, "origin": "schedule_and_ config_updater.py/update_local_scheduling_files:138", "origin_timestamp": "2024-10-14-21-45-35", "registration_timestamp": "2024-10-14-21-45-35"}
{"timestamp": "2024-10-15-00-00-03", "message": "Module error while trying to update local copy of override_rooms: failed to set up Google Sheets API: <HttpError 404 when requesting https://sheets.googleapis.com/v4/spreadsheets/https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1Cir4TYYhIx14Qja9c4nN9m2GTeZ0FHrJRt03oXs_fgI%2Fpub%3Foutput%3Dcsv?alt=json returned \"Requested entity was not found.\". Details: \"Requested entity was not found.\"> (HttpError).", "severity": 3, "origin": "schedule_and_ config_updater.py/update_local_scheduling_files:138 --> project.py/download_google_sheet_to_2D_array:1501", "origin_timestamp": "2024-10-14-21-54-34", "registration_timestamp": "2024-10-14-21-54-34"}
{"timestamp": "2024-10-15-00-00-03", "message": "Module error while trying to update local copy of weekly_cycle/8: failed to download sheet 'kisterem' from spreadsheet 'f\u0171t\u00e9s heti ciklus 24/25':  (KeyboardInterrupt).", "severity": 3, "origin": "schedule_and_ config_updater.py/update_local_scheduling_files:138 --> project.py/download_google_sheet_to_2D_array:1523", "origin_timestamp": "2024-10-14-22-05-35", "registration_timestamp": "2024-10-14-22-05-35"}
{"timestamp": "2024-10-15-09-21-34", "message": "Module error while trying to acquire temperature and humidity data: couldn't read sensor state due to: failed to connect to Deconz API due to unexpected error: Error requesting data from 192.168.29.54: Cannot connect to host 192.168.29.54:80 ssl:default [Network is unreachable] (RequestError) (ModuleException).", "severity": 3, "origin": "temperature_and_humidity_logger.py:10 --> project.py/get_room_temps_and_humidity:775", "origin_timestamp": "2024-10-15-09-21-34", "registration_timestamp": "2024-10-15-09-21-34"}
