{"timestamp": "2024-10-17-02-40-03", "message": "Module error while exporting system state: failed to interact with node 'system' via patch: HTTPSConnectionPool(host='kazanfutes-71b78-default-rtdb.europe-west1.firebasedatabase.app', port=443): Max retries exceeded with url: /system/state.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf5a2f6b0>: Failed to establish a new connection: [Errno 101] Network is unreachable')) (ConnectionError).", "severity": 3, "origin": "heating_control.py/get_and_export_system_state:140 --> project.py/write:280 --> project.py/interact:260", "origin_timestamp": "2024-10-17-02-38-20", "registration_timestamp": "2024-10-17-02-38-20"}
